/**
 * Generated by Config Editor on 2026-06-24T06:49:48.435Z
 *
 * Yalnızca editörde değiştirilen değerler merkezi konfigürasyonla birleştirildi.
 * Bu dosyayı olduğu gibi "src/core/config.js" üzerine kaydedebilirsin.
 */

export const config = {
    interfaces: ['web', 'mobile'],
    initialView: 'auto',
    branding: {
        logo: 'https://hedeffiyat.com.tr/resimler/senet/emlak-konut-gayrimenkul-yatirim-ortakligi-a.s.-92.png',
        title: 'EMLAK KONUT',
        subtitle: 'ANAHTAR FİKİRLER'
    },
    navbar: {
        enabled: true,
        clock: true,
        logo: true,
        langSwitcher: true
    },
    theme: {
        backgroundGradient: ['#d0c8c8', '#cbbebe', '#c4c8cf'],
        solidSurface: 'rgb(248, 245, 245)',
        accentColor: '#111111',
        accentHover: '#4f46e5',
        textPrimary: 'rgba(19, 18, 18, 0.95)',
        textSecondary: 'rgba(0, 0, 0, 0.75)',
        textMuted: 'rgba(230, 0, 0, 0.5)',
        glassEnabled: true,
        glassBackground: 'rgba(255, 255, 255, 0.12)',
        glassBorder: 'rgba(255, 255, 255, 0.18)',
        glassBlur: '25px',
        cardBorder: 'rgba(0, 0, 0, 0.14)',
        mobile: {
            sheetBackground: '#ffffff',
            sheetShadow: 'rgba(0, 0, 0, 0.12)',
            cardBackground: '#f3f4f6',
            cardBorder: '#e5e7eb',
            surfaceBackground: '#f9fafb',
            textPrimary: null,
            textSecondary: null,
            textMuted: null,
            dangerBackground: '#fef2f2',
            dangerColor: '#dc2626',
            progressGradientEnd: null,
            categoryGrid: {
                defaultColumns: 3,
                rows: []
            }
        }
    },
    venue: {
        name: 'Terminal Kadıköy',
        dataSource: 'sheets',
        api: {
            baseUrl: 'https://api.inmapper.com/zorlu-center'
        },
        sheets: {
            sheetId: '18OoZeGvuAQTVlIKu-80uXMpxu5AdbBR6qDKRWjr9PVw',
            tabs: {
                list: 'AnahtarFikir_List',
                categories: 'AnahtarFikir_Categories',
                info: 'Info'
            },
            writeEndpointUrl: '',
            gid: '0'
        },
        geojsonPath: 'assets/venue.geojson',
        routing: {
            venueSlug: 'zorlu',
            routeUrl: 'http://localhost:5002/api/route',
            describeUrl: 'http://localhost:5002/api/describe',
            // Routing API erişilemez/başarısız olduğunda tarayıcı içi
            // pathfinder ile rota hesaplanır. `false` ile kapatılabilir.
            fallbackToLocal: true,
            // Aşamalı tarif motoru:
            //   'ml'     → backend insan-tarifli describe API (describeUrl)
            //   'metric' → tarayıcı içi metrik tarif motoru (route-engine plugin)
            descriptionEngine: 'ml'
        },
        categoryMappingFile: 'category-mapping.json',
        cacheDuration: 300000,
        floorMap: {
            "0": 'Zemin Kat'
        },
        defaultFloor: '0',
        kioskLocation: {
            id: 0,
            name: 'Bulunduğunuz Konum',
            category: 'Kiosk',
            floor: 'Zemin Kat',
            type: 'kiosk',
            icon: '📍'
        }
    },
    features: {
        data: {
            enabled: true
        },
        map: {
            enabled: true,
            center: [29.036874, 40.991633],
            pitch: 60,
            bearing: -20,
            zoom: 17,
            sublayerColors: {
                walking: '#f5f5f5',
                building: '#e6e6e6',
                stand: '#d9d3d2',
                service: '#e9dad0',
                food: '#d1bbbc',
                water: '#cfe2f3',
                other: '#e9dad0',
                shop: '#d9d3d2',
                green: '#a8d08d',
                medical: '#ff9999',
                commercial: '#ffe0b2',
                social: '#c5cae9',
                structure: '#d0d0d0'
            },
            sublayerHeights: {
                walking: 0,
                building: 0,
                stand: 8,
                service: 6,
                food: 6,
                water: 0.5,
                other: 5,
                shop: 8,
                green: 1,
                medical: 6,
                commercial: 7,
                social: 5,
                structure: 3,
                layer6: 3,
                layer7: 1,
                layer9: 3,
                layer10: 1,
                layer11: 3
            },
            shrinkFactor: 0.99,
            roomRenderMode: 'walls',
            renderModeBySublayer: {
                layer10: 'solid',
                layer7: 'solid',
                layer6: 'walls',
                layer11: 'walls'
            },
            wallThickness: 0.2,
            wallColorMode: 'fixed',
            wallColor: '#d9d3d2',
            doorGaps: true,
            doorGapWidth: 1.4,
            // Kapı boşluğu açma yöntemi:
            //   'doors' → kapının bağlı olduğu path'in duvarı kestiği yer
            //   'paths' → kapı gözetmeksizin tüm path'lerin duvarı kestiği her yer
            doorGapMode: 'doors',
            // Devre dışı (disabled) birimlerin görünümü:
            //   colored=false → tamamen görünmez
            //   colored=true  → `color` ile düz blok olarak gösterilir
            //                   (örn. kapalı mağazaları belirtmek için)
            //   showLabel     → devre dışı birimin başlığı gösterilsin mi
            disabledUnits: {
                colored: false,
                color: '#9ca3af',
                showLabel: false
            },
            showOtherFloorOutlines: false,
            tileOpacity: 0.6,
            overlayOpacity: 0.35,
            interaction: {
                hover: true,
                click: true,
                hoverColor: '#93c5fd',
                selectedColor: '#3b82f6',
                routeStartColor: '#22c55e',
                routeEndColor: '#3b82f6',
                flyToDuration: 800,
                flyToMaxZoom: 20,
                flyToPadding: 120
            },
            labels: {
                normalization: true,
                minZoom: {
                    sm: 14,
                    md: 13,
                    lg: 12
                },
                collisionEnabled: true,
                textColor: '#1a1a1a',
                haloColor: 'rgba(255,255,255,0.9)',
                pitchAlignment: 'viewport',
                translateAnchor: 'viewport',
                translateStops: [15, 0, 17, -12, 18, -20, 19, -30, 20, -45, 21, -65]
            },
            route: {
                color: '#2563EB',
                glowColor: '#2563EB',
                glowOpacity: 0.25,
                outlineColor: '#1e40af',
                // Rota çizgi kalınlığı çarpanı (1 = varsayılan). Glow/kenarlık/iç
                // çizgi genişlikleri bu oranla birlikte ölçeklenir.
                width: 1,
                animateDraw: true,
                drawDuration: 2000,
                drawEasing: 'easeInOutCubic',
                arrows: {
                    enabled: true,
                    animated: true,
                    count: 6,
                    speed: 0.06,
                    color: '#ffffff',
                    opacity: 0.9,
                    iconUrl: null,
                    rotateWithPath: true,
                    size: 1
                },
                overviewFirst: true,
                navCameraZoom: 20,
                navCameraPitch: 65
            }
        },
        models3d: {
            enabled: true,
            models: [
        {
            id: "chobani-stadium",
            url: "assets/models/Football Stadium.glb",
            origin: [29.036546,40.988108],
            altitude: 0,
            rotation: [Math.PI / 2, 0, 0],
            scale: 3,
        },
        {
            id: "kadikoy-belediyesi",
            url: "assets/models/Town Hall.glb",
            origin: [29.0372,40.9933],
            altitude: 0,
            rotation: [Math.PI / 2, 0, 0],
            scale: 0.02,
        }
    ]
        },
        search: {
            enabled: true
        },
        navigation: {
            enabled: true,
            qrBaseUrl: 'https://zorlu.center/route',
            startPointMode: 'manual',
            routeTypes: [
                {
                    key: 'shortest',
                    label: 'En Kısa',
                    icon: 'stepStraight'
                },
                {
                    key: 'least_turns',
                    label: 'Az Dönüş',
                    icon: 'stepRight'
                }
            ],
            droppedPin: {
                enabled: true,
                pinColor: '#3b82f6',
                cursorColor: '#f97316',
                snapToPath: true
            }
        },
        sidePanel: {
            enabled: true,
            defaultSide: 'right',
            layout: 'island',
            island: {
                position: 'top-left',
                width: 500,
                maxHeight: '70vh',
                compactVisibleRows: 3,
                margin: 20,
                borderRadius: 20
            }
        },
        keyboard: {
            enabled: true,
            defaultLanguage: 'tr',
            languages: ['tr', 'en', 'zh', 'ar']
        },
        home: {
            enabled: true,
            slideshow: true,
            searchBar: true,
            categoryCards: true,
            exploreMapBtn: true,
            visibleCategories: null
        },
        floorSelector: {
            enabled: true
        },
        clock: {
            enabled: true
        },
        idle: {
            enabled: true,
            timeout: 90000
        },
        storeDetail: {
            enabled: true
        },
        messaging: {
            enabled: true
        },
        assistant: {
            enabled: true,
            voice: true,
            language: 'tr',
            suggestions: null
        },
        editMode: {
            enabled: false
        }
    }
};
